/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ape.ui;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;

/**
 *
 * @author Gabriel
 */
public class MainFrame extends javax.swing.JFrame {

  public static final int TOP_PANEL = 0;
  public static final int LEFT_PANEL = 10;
  
  public static final int TOP_RIGHT_PANEL = 20;
  public static final int BOTTOM_RIGHT_PANEL = 30;
  
  public static final int BOTTOM_PANEL = 40;
  public static final int CENTER_PANEL = 50;
  
  
  /**
    * Creates new form MainFrame
    */
  public MainFrame() {
    initComponents();
    setSize(800,600);
  }
  
  public void addTo(Component c, int where, boolean setSizeToContent) {
    Container container = getContainer(where);
    container.add(c);
    if(setSizeToContent) {
      container.setMinimumSize(c.getMinimumSize());
      container.setMaximumSize(c.getMaximumSize());
      container.setSize(c.getSize());
    }
  }
  
  private Container getContainer(int where) {
    Container container;
    switch (where) {
      case TOP_PANEL:
        container = topPane;
        break;
      case LEFT_PANEL:
        container = leftPane;
        break;
      case TOP_RIGHT_PANEL:
        container = topRightPane;
        break;
      case BOTTOM_RIGHT_PANEL:
        container = bottomRightPane;
        break;
      case BOTTOM_PANEL:
        container = bottomPane;
        break;
      case CENTER_PANEL:
      default:
        container = centerPane;
        break;
    }
    return container;
  }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        bottomPane = new javax.swing.JPanel();
        centerPane = new javax.swing.JPanel();
        topPane = new javax.swing.JPanel();
        leftPane = new javax.swing.JPanel();
        rightPane = new javax.swing.JPanel();
        jSplitPane5 = new javax.swing.JSplitPane();
        topRightPane = new javax.swing.JPanel();
        bottomRightPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane1.setResizeWeight(0.99);
        jSplitPane1.setToolTipText("");
        jSplitPane1.setOneTouchExpandable(true);

        jSplitPane2.setResizeWeight(0.01);
        jSplitPane2.setOneTouchExpandable(true);

        jSplitPane3.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane3.setResizeWeight(0.01);
        jSplitPane3.setToolTipText("");
        jSplitPane3.setOneTouchExpandable(true);

        jSplitPane4.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane4.setResizeWeight(0.99);
        jSplitPane4.setToolTipText("");
        jSplitPane4.setOneTouchExpandable(true);

        bottomPane.setMaximumSize(new java.awt.Dimension(32767, 200));
        bottomPane.setMinimumSize(new java.awt.Dimension(0, 20));
        bottomPane.setPreferredSize(new java.awt.Dimension(100, 50));
        bottomPane.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane4.setBottomComponent(bottomPane);

        centerPane.setMinimumSize(new java.awt.Dimension(300, 300));
        centerPane.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane4.setLeftComponent(centerPane);

        jSplitPane3.setBottomComponent(jSplitPane4);

        topPane.setMaximumSize(new java.awt.Dimension(32767, 40));
        topPane.setMinimumSize(new java.awt.Dimension(0, 30));
        topPane.setPreferredSize(new java.awt.Dimension(100, 30));
        topPane.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane3.setLeftComponent(topPane);

        jSplitPane2.setRightComponent(jSplitPane3);

        leftPane.setMaximumSize(new java.awt.Dimension(300, 32767));
        leftPane.setMinimumSize(new java.awt.Dimension(150, 0));
        leftPane.setName("leftPane");
        leftPane.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane2.setLeftComponent(leftPane);
        leftPane.getAccessibleContext().setAccessibleName("");

        jSplitPane1.setLeftComponent(jSplitPane2);

        rightPane.setMaximumSize(new java.awt.Dimension(250, 32767));
        rightPane.setMinimumSize(new java.awt.Dimension(150, 0));
        rightPane.setLayout(new java.awt.GridLayout(1, 0));

        jSplitPane5.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane5.setResizeWeight(0.7);
        jSplitPane5.setMaximumSize(new java.awt.Dimension(250, 2147483647));
        jSplitPane5.setOneTouchExpandable(true);

        topRightPane.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane5.setTopComponent(topRightPane);

        bottomRightPane.setMaximumSize(new java.awt.Dimension(250, 32767));
        bottomRightPane.setLayout(new java.awt.GridLayout(1, 0));
        jSplitPane5.setRightComponent(bottomRightPane);

        rightPane.add(jSplitPane5);

        jSplitPane1.setRightComponent(rightPane);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPane;
    private javax.swing.JPanel bottomRightPane;
    private javax.swing.JPanel centerPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JPanel leftPane;
    private javax.swing.JPanel rightPane;
    private javax.swing.JPanel topPane;
    private javax.swing.JPanel topRightPane;
    // End of variables declaration//GEN-END:variables

}
